apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-build-docker
  namespace: loginapp-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: login-app-docker-strat:latest
  source:
    type: Git
    git:
      uri: 'https://github.com/walidelbiir/redhat-loginapp.git'
      ref: "main"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-tomcat  
  triggers:
    - type: ConfigChange
    