apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-build-docker
  namespace: loginapp-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: login-app-docker-strat
  source:
    type: Git
    git:
      uri: git@github.com:walidelbiir/redhat-loginapp.git
      ref: "main"
    sourceSecret:
      name: repo-at-github
  serviceAccount : builder
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-tomcat 
  triggers:
    - type: ConfigChange
    