apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loginapp-dev

generatorOptions:
  disableNameSuffixHash: true

namespace: loginapp-dev

resources:
- ../../base
- ./pv.yaml
- ./pvc.yaml




