apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: loginapp-dev

resources:
- ../../base

configMapGenerator:
- name: login-app-config-map
  envs:
  - loginapp.properties
  options:
    labels:
      app: login-app


secretGenerator:
- name: login-app-secret
  envs:
  - loginapp.secret
  type: Opaque
  options:
    labels:
      app: login-app