kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.195.11
    path: /mnt/data/nfs/mysql
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
  volumeMode: Filesystem
