apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-s2i

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base

patches:
- path: ./patches/image_patch.yaml
- path: ./patches/pv_patch.yaml
  target: 
    kind: PersistentVolume
    name: mysql-docker-pv
- path: ./patches/pvc_patch.yaml
  target:
    kind: PersistentVolumeClain
    name: mysql-docker-pv

