apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-custom

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base

patches:
- path: ./patches/image_patch.yaml

