apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-openshift-pipeline

spec:

  params:
    - name: SCRIPT
      type: string
    - name: URL
      type: string

  workspaces:
    - name: manifest-dir
      description: This workspace contains the yaml files
    #- name: ssh-creds
    #  description: This workspace contains the ssh key for the git repo


  tasks:
    #  description: This workspace contains the ssh key for the git repo
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.URL)
      workspaces:
        #- name: ssh-directory
        #  workspace: ssh-creds
        - name: output
          workspace: manifest-dir

    - name: execute-build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter: ["fetch-source"]
      params:
        - name: SCRIPT
          value: $(params.SCRIPT)
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
