apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-build-s2i-builder
  namespace: loginapp-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: login-app-s2i-builder:latest
  source:
    type: Git
    git:
      uri: git@github.com:walidelbiir/redhat-loginapp.git
      ref: "main"
    sourceSecret:
      name: repo-at-github
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-customBuilder  
  triggers:
    - type: ConfigChange
    