apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  namespace: loginapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: image-registry.openshift-image-registry.svc:5000/loginapp-dev/login-app-docker-strat
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: login-app-secret
                  key: USER
                  
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: login-app-secret
                  key: PASS

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: login-app-config-map
                  key: DB_URL

            - name: DBC_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: login-app-config-map
                  key: DBC_DRIVER

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: login-app-config-map
                  key: DB_NAME