apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: loginapp-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: crc-csi-hostpath-provisioner