apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: loginapp-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: mysql-storage