apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: loginapp-prod

resources:
- ../dev

patches:
- path: ./patches/replica_count_patch.yaml
- path: ./patches/image_patch.yaml

