apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: login-app
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: login-app:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source