apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-custom-strat-build
spec:
  source:
    git:
      uri: 'https://github.com/walidelbiir/redhat-loginapp.git'
  serviceAccount: builder
  strategy:
    type: Custom
    customStrategy:
      from:
        kind: ImageStreamTag
        name: 'login-app-custom-image:latest'
      env:
        - name: REDHAT_USERNAME
          valueFrom:
            secretKeyRef:
              name: redhat-login-credentials
              key: USERNAME
        - name: REDHAT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redhat-login-credentials
              key: PASSWORD
        - name: SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: redhat-login-credentials
              key: SERVICE_ACCOUNT
  output:
    to:
      kind: ImageStreamTag
      name: 'login-app-custom-strat:latest'