apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: login-app-custom-strat
  namespace: loginapp-dev
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: login-app-custom-strat:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source