apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-dev

generatorOptions:
  disableNameSuffixHash: true
  
resources:
  - BuildConfigCustomStrat.yaml
  - ImageStreamCustom.yaml
  - ./CustomImageBuilder/ImageStreamCustom.yaml
  - ./CustomImageBuilder/BuildConfigCustomImage.yaml

secretGenerator:
- name: redhat-login-credentials
  envs:
  - redhat-login.credentials
  type: Opaque
- name: github-pat
  envs:
  - github-pat
  type: Opaque