apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-build-s2i
  namespace: loginapp-dev
spec:
  source:
    git:
      uri: git@github.com:walidelbiir/redhat-loginapp.git
    type: Git
    sourceSecret:
      name: repo-at-github
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: "image-registry.openshift-image-registry.svc:5000/loginapp-dev/eap-xp4-openjdk11-openshift-rhel8:latest"
    type: Source
  serviceAccount: builder
  output:
    to:
      kind: ImageStreamTag
      name: login-app-s2i-strat:latest