apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-argocd

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base
- ./pv.yaml
- ./pvc.yaml

patches:
- path: ./patches/image_patch.yaml
- path: ./patches/mysql_pvc_patch.yaml
