apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-customs2i

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base
- ./pv.yaml
- ./pvc.yaml
- "!../../base/database/mysql-pv.yaml"
- "!../../base/database/mysql-pvc.yaml"

patches:
- path: ./patches/image_patch.yaml


