apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loginapp-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/walidelbiir/loginapp-config.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: loginapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true