apiVersion: v1
kind: Secret
metadata:
  name: redhat-registry-secret
  annotations:
    tekton.dev/docker-0: registry.redhat.io
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
    "auths": {
      "registry.redhat.io": {
        "auth": "MTgyNzI3Mzl8dGVrdG9uLXBpcGVsaW5lOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJNVlUTmpZek16T0RGaVl6ZzBNVEUzT0RBNFl6TTBaV0ZrWWpVek5tSm1aQ0o5LkRjb1FKT2d5elRJUWM3V1pCUFluZ2ExR3VWVDJ2OWx4ZDgwMEJ5RDhZaU5lZU5jTFBuVjktWEF0RUU2ZDB3d2JjVFk1ZTBPYS00V1hETUYzVjU1eW5KMEN0azBTU3Z4U2tVMnpvdXRZWHYtLTRBNzNuUkREa0dzR1lGZ3VaZks5Q1JnVHFfZmNsQnZOc2g3TFVpRHZwSWFPSHJHZ2RGRmgzSHFvSS1ZQW1Oa05zNkVycFh3bjhfd0tndDJvT1hUSWhyRU5XbzNXUXZlRVcyY25HOUVWUUVvckpITHptRUVkNXU3SllhT19ENm8wM3p1dUtWbTlDaGpIMk1mMTlrN09XaFFwQnlkOFhmMEFtRnc1d0M3RlVXNmlVZGYwUXFuYm41alRjaFV0UmlBMkZYNGJVQ1o5TVRFX3pnc21zQmVGSi1DbVc0YWJfc3lGR1hTcVp5WkFucmg3VW1tSXdQaG9qTGNobVhxUG9DclF1WWxBME1QQWtGbjlGWFhKUGNVanI2QnhabTh1S2EzaTdmZnl5cm1JYUdURk80R3ZlRUlqOXhSeHFYSE9faklKOS1xbmEwTU1JaXgzaEdHN0lKaXZzVkNjZUJ5amtfNjhBeTBfN3pTdGl0dGVkbmhhUDVlUTdWUWxPQTlrekUwY1BoUndxbzdfOGdab0hKQXNIVTAyOFdzU2tUS0VWOWR5Z3cwZ3FISHZlUlNZRnBVWHlfYVNDdW5QRklwVlU2U0lnS1oxMGVFbzNXMmZmdXRxaWtTQTRDekthT3N6MV81cUFOSHp5X0RpWmpicHFveU1JSkJ0QUl5clJfOVZ0cmFUdzFJLTd1QUVYWkRDSXRKdDF6MGhLQUVZR3RfdEdoT2VUdU5PcWRFV2p6MUlqR2x6U1dOeGNPc25tekZBN21J"
      }
    }
    }

