apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: loginapp-dev-pipeline-run-test
  namespace: loginapp-dev
spec:
  pipelineRef:
    name: loginapp-dev-pipeline
  serviceAccountName: pipeline
  params:
    - name: URL
      value: git@github.com:walidelbiir/redhat-loginapp.git
    - name: TLSVERIFY
      value: false
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/loginapp-dev/tekton-pipeline-image:latest
  workspaces:
    - name: sourceCode
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    #- name: ssh-creds
    #  secret:
    #    secretName: repo-at-github
    #- name: dockerconfig
    #  secret:
    #    secretName: dockerconfig-secret