apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: loginapp-dev-pipeline

spec:

  params:
    - name: URL
      type: string
    - name: TLSVERIFY
      type: string
    - name: IMAGE
      type: string


  workspaces:
    - name: sourceCode
      description: This workspace contains the repo files


  tasks:

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.URL)
      workspaces:
        - name: output
          workspace: sourceCode
    
    - name: build-and-push
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter: ["git-clone"]
      params:
        - name: TLSVERIFY
          value: $(params.TLSVERIFY)
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: sourceCode
