apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  namespace: loginapp-dev

spec:
  template:
    spec:
      containers:
        - name: login-app
          image: image-registry.openshift-image-registry.svc:5000/loginapp-dev/login-app-custom-strat:latest
 