apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loginapp-dev

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./LoginApp/
  - ./Database/
  - ./ssh-git-secret.yaml

configMapGenerator:
- name: login-app-config-map
  envs:
  - loginapp.properties
  options:
    labels:
      app: login-app


secretGenerator:
- name: login-app-secret
  envs:
  - loginapp.secret
  type: Opaque
  options:
    labels:
      app: login-app
- name: mysql
  envs:
  - database.secret
  type: Opaque
