apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    app.openshift.io/runtime: mysql-database

spec:
  template:
    spec:
      volumes:
        - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-custom-s2i-pvc