apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: login-app-build-s2i-custom
  namespace: loginapp-dev
spec:
  source:
    git:
      uri: git@github.com:walidelbiir/redhat-loginapp.git
    type: Git
    sourceSecret:
      name: repo-at-github
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: login-app-s2i-builder:latest
    type: Source
  serviceAccount: builder
  output:
    to:
      kind: ImageStreamTag
      name: login-app-s2i-custom:latest