apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  
resources:
  - BuildConfigCustomS2I.yaml
  - ImageStreamCustomS2I.yaml
  - ./BuilderImage/BuildConfigBuilderImage.yaml
  - ./BuilderImage/ImageStreamBuilderImage.yaml
